'use strict';
const cards=window.STUDY_DATA.cards;
const $=id=>document.getElementById(id);
let index=0,revealed=false,playing=false,timer=null;
const key='isye6501-midterm1-simple-position-v1';
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&Number.isInteger(saved.index)&&saved.index>=0&&saved.index<cards.length)index=saved.index;if(saved&&[5,10,15].includes(saved.interval))$('interval').value=String(saved.interval);}catch(e){/* Cards still work when browser storage is unavailable. */}
function persist(){try{localStorage.setItem(key,JSON.stringify({index,interval:Number($('interval').value)}));}catch(e){/* Saving position is optional; navigation does not depend on it. */}}
function text(tag,value){const node=document.createElement(tag);node.textContent=value;return node;}
const svgs={
vertical:`<path d="M50 20V205H380"/><text x="386" y="209">x₁</text><text x="22" y="20">x₂</text><line class="decision" x1="205" y1="22" x2="205" y2="200"/><text x="105" y="235">negative</text><text x="255" y="235">positive</text><text x="189" y="219">4</text>`,
horizontal:`<path d="M50 20V205H380"/><text x="386" y="209">x₁</text><text x="22" y="20">x₂</text><line class="decision" x1="55" y1="115" x2="375" y2="115"/><text x="170" y="65">positive</text><text x="170" y="170">negative</text>`,
tree:`<path d="M210 58L90 115M210 58L305 105M305 140L220 195M305 140L375 195"/><rect x="148" y="15" width="125" height="43" rx="5"/><text x="171" y="43">x₁ &lt; 4 ?</text><rect x="250" y="99" width="113" height="41" rx="5"/><text x="270" y="126">x₂ &gt; 2 ?</text><rect x="28" y="114" width="118" height="61" rx="5"/><text x="41" y="139">Left: negative</text><text x="57" y="160">17 / 20</text><rect x="159" y="193" width="122" height="55" rx="5"/><text x="170" y="216">Middle: positive</text><text x="190" y="239">18 / 20</text><rect x="309" y="193" width="102" height="55" rx="5"/><text x="317" y="216">Right: negative</text><text x="350" y="239">1 / 1</text><text x="103" y="83">YES</text><text x="276" y="80">NO</text><text x="232" y="166">YES</text><text x="363" y="166">NO</text>`,
elbow:`<path d="M50 25V205H380M85 40L145 129L205 180L265 186L325 189"/><text x="18" y="20">WSS</text><text x="385" y="210">k</text><circle cx="85" cy="40" r="4"/><circle cx="145" cy="129" r="4"/><circle cx="205" cy="180" r="4"/><circle cx="265" cy="186" r="4"/><circle cx="325" cy="189" r="4"/><text x="82" y="228">1</text><text x="142" y="228">2</text><text x="202" y="228">3</text><text x="262" y="228">4</text><text x="322" y="228">5</text><text x="67" y="32">420</text><text x="130" y="114">230</text><text x="75" y="254">WSS: 420 → 230 → 120 → 108 → 101</text>`,
pca:`<path d="M50 25V205H380"/><text x="386" y="210">x₁</text><text x="25" y="21">x₂</text><circle cx="88" cy="177" r="5"/><circle cx="121" cy="155" r="5"/><circle cx="147" cy="142" r="5"/><circle cx="177" cy="130" r="5"/><circle cx="206" cy="112" r="5"/><circle cx="241" cy="92" r="5"/><circle cx="278" cy="77" r="5"/><circle cx="319" cy="57" r="5"/><circle cx="343" cy="39" r="5"/>`,
clusters:`<path d="M50 25V205H380"/><text x="130" y="234">Circles: day · Squares: night</text><circle cx="80" cy="60" r="6"/><circle cx="99" cy="72" r="6"/><circle cx="123" cy="51" r="6"/><circle cx="101" cy="100" r="6"/><circle cx="142" cy="83" r="6"/><circle cx="155" cy="55" r="6"/><rect x="269" y="137" width="11" height="11"/><rect x="303" y="160" width="11" height="11"/><rect x="330" y="127" width="11" height="11"/><rect x="292" y="113" width="11" height="11"/><rect x="343" y="165" width="11" height="11"/>`
};
const diagramText={vertical:'The horizontal axis is x₁ and the vertical axis is x₂. A vertical dashed boundary is at x₁=4. The region to its left is negative; the region to its right is positive.',horizontal:'The horizontal axis is x₁ and the vertical axis is x₂. A horizontal dashed boundary separates positive above from negative below.',tree:'First test x₁ < 4: YES goes to the left negative leaf, with 17 of 20 correct. NO goes to x₂ > 2: YES goes to the middle positive leaf, with 18 of 20 correct; NO goes to the right negative leaf, with 1 of 1 correct.',elbow:'For cluster counts k=1,2,3,4,5, WSS is respectively 420,230,120,108,101. Both axes increase in their labeled direction.',pca:'A scatter plot of two standardized predictors has points clustered close to a rising diagonal line.',clusters:'Daytime circles are concentrated in the upper-left region, and nighttime squares in the lower-right region.'};

function drawDiagram(card){$('diagram').replaceChildren();if(!card.diagram||!svgs[card.diagram])return;const content=document.createElement('div');content.innerHTML=`<svg viewBox="0 0 440 260" role="img" aria-label="${diagramText[card.diagram]}">${svgs[card.diagram]}</svg>`;const details=document.createElement('details');details.append(text('summary','Read diagram as text'),text('p',diagramText[card.diagram]));$('diagram').append(content,details);}
function render(){const card=cards[index];$('position').textContent=`Card ${index+1} of ${cards.length}`;$('module').textContent=`Module ${card.module}`;$('question').textContent=card.stem;$('choices').replaceChildren();const options=card.options||[];options.forEach(option=>$('choices').append(text('li',option)));$('choices').hidden=!options.length;drawDiagram(card);$('answer').textContent=card.answer;$('explanation').textContent=card.explanation===card.answer?'':card.explanation;$('explanation').hidden=!$('explanation').textContent;$('takeaway').textContent=card.takeaway?'Remember: '+card.takeaway:'';$('takeaway').hidden=!card.takeaway;$('links').replaceChildren();for(const [i,link]of(card.links||[]).entries()){if(i)$('links').append(document.createTextNode(' · '));const a=text('a',link.label);a.href=link.url;a.target='_blank';a.rel='noopener noreferrer';$('links').append(a);}$('links').hidden=!(card.links||[]).length;$('answer-panel').hidden=!revealed;$('reveal').textContent=revealed?'Hide answer':'Reveal answer';$('reveal').setAttribute('aria-expanded',String(revealed));$('previous').disabled=index===0;$('next').disabled=index===cards.length-1;persist();}
function updateStatus(){ $('autoplay').textContent=playing?'⏸ Pause':'▶ Auto-play';$('autoplay').setAttribute('aria-pressed',String(playing));$('play-status').textContent=playing?`${revealed?'Answer':'Question'} · ${$('interval').value}s`:index===cards.length-1&&revealed?'End of deck':'Paused';}
function pause(){playing=false;if(timer!==null){clearTimeout(timer);timer=null;}updateStatus();}
function schedule(){if(timer!==null)clearTimeout(timer);if(!playing)return;const delay=Number($('interval').value)*1000;timer=setTimeout(()=>{timer=null;if(!playing)return;if(!revealed)revealed=true;else if(index<cards.length-1){index++;revealed=false;}else{pause();return;}render();updateStatus();schedule();},delay);}
function move(delta){pause();const next=index+delta;if(next<0||next>=cards.length)return;index=next;revealed=false;render();updateStatus();}
function toggleAnswer(){pause();revealed=!revealed;render();updateStatus();}
function togglePlay(){if(playing){pause();return;}playing=true;updateStatus();schedule();}
$('previous').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('reveal').onclick=toggleAnswer;$('autoplay').onclick=togglePlay;$('interval').onchange=()=>{persist();if(playing)schedule();updateStatus();};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select,button,a,summary')||e.altKey||e.ctrlKey||e.metaKey||e.repeat)return;if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}else if(e.key==='ArrowRight'){e.preventDefault();move(1);}else if(e.code==='Space'){e.preventDefault();toggleAnswer();}else if(e.key.toLowerCase()==='p'){e.preventDefault();togglePlay();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
render();updateStatus();window.FLASHCARDS_READY=true;
